/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.factura;

import dao.ClienteDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.TableColumn;
import model.Cliente;
import services.ClienteService;
import view.usuario.Login;

/**
 *
 * @author gamert
 */
public class ListaClientes extends javax.swing.JInternalFrame {
    private ClienteTableModel clienteTableModel;
    private Connection connection;
    private ClienteService clienteService;
    private AgregarCliente agregarCliente;
    /**
     * Creates new form ListaClientes
     */
    public ListaClientes(Connection connection) {
        initComponents();
        this.connection = connection;
        clienteService = new ClienteService(connection);
        cargarClientes(); 
        agregarCliente = new AgregarCliente();
        agregarCliente.setListaClientes(this);
        agregarCliente.setClienteService(clienteService);
        
        // Agregar un listener para maximizar el JInternalFrame cuando se abre
        this.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
                try {
                    setMaximum(true); // Maximiza el JInternalFrame
                } catch (java.beans.PropertyVetoException ex) {
                    Logger.getLogger(ListaClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        tblClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "RUC", "Nombre", "Dirección", "Acción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setRowHeight(40);
        jScrollPane1.setViewportView(tblClientes);

        btnAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        setBounds(0, 0, 821, 552);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarClientes() {
        try {
        // Verificar que el servicio no sea null
            if (clienteService == null) {
                throw new IllegalStateException("ClienteService no ha sido inicializado.");
            }

            // Obtener la lista de clientes desde la base de datos
            List<Cliente> clientes = clienteService.obtenerTodosLosClientes();

            // Verificar que la lista de clientes no sea null
            if (clientes == null) {
                throw new IllegalStateException("La lista de clientes es null.");
            }

            // Crear el modelo de tabla y configurarlo en la tabla
            clienteTableModel = new ClienteTableModel(clientes);
            tblClientes.setModel(clienteTableModel);
            
            // Ajustar el ancho de las columnas
            TableColumn column;
            for (int i = 0; i < tblClientes.getColumnCount(); i++) {
                column = tblClientes.getColumnModel().getColumn(i);
                if (i == 0) { // Columna "ID"
                    column.setPreferredWidth(50);
                } else if (i == 1) { // Columna "RUC"
                    column.setPreferredWidth(100);
                } else if (i == 2) { // Columna "Nombre"
                    column.setPreferredWidth(150);
                } else if (i == 3) { // Columna "Dirección"
                    column.setPreferredWidth(200);
                } else if (i == 4) { // Columna "Acción"
                    column.setPreferredWidth(150);
                }
            }

            // Configurar la columna de "Acciones" con los botones
            TableColumn actionColumn = tblClientes.getColumnModel().getColumn(4);
            actionColumn.setCellRenderer(new ClientButtonColumn(tblClientes, clienteService));
            actionColumn.setCellEditor(new ClientButtonColumn(tblClientes, clienteService));
        } catch (SQLException e) {
            Logger.getLogger(ListaClientes.class.getName()).log(Level.SEVERE, "Error SQL al cargar clientes", e);
        } catch (IllegalStateException e) {
            Logger.getLogger(ListaClientes.class.getName()).log(Level.SEVERE, "Estado ilegal al cargar clientes", e);
        } catch (Exception e) {
            Logger.getLogger(ListaClientes.class.getName()).log(Level.SEVERE, "Error desconocido al cargar clientes", e);
        }
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarCliente.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void addCliente(Cliente cliente){
        // Agregar el cliente al modelo de la tabla
        clienteTableModel.getClientes().add(cliente);        
        // Notificar al modelo de la tabla que los datos han cambiado
        clienteTableModel.fireTableDataChanged();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
